export const hiraganaList = {
  a: [
    {romaji: 'a', translated: '\u3042', isBig: true},
    {romaji: 'i', translated: '\u3044', isBig: true},
    {romaji: 'u', translated: '\u3046', isBig: true},
    {romaji: 'e', translated: '\u3048', isBig: true},
    {romaji: 'o', translated: '\u304A', isBig: true},
  ],
  ka: [
    {romaji: 'ka', translated: '\u304B', isBig: true},
    {romaji: 'ki', translated: '\u304D', isBig: true},
    {romaji: 'ku', translated: '\u304F', isBig: true},
    {romaji: 'ke', translated: '\u3051', isBig: true},
    {romaji: 'ko', translated: '\u3053', isBig: true},
  ],
  sa: [
    {romaji: 'sa', translated: '\u3055', isBig: true},
    {romaji: 'shi', translated: '\u3057', isBig: true},
    {romaji: 'su', translated: '\u3059', isBig: true},
    {romaji: 'se', translated: '\u305B', isBig: true},
    {romaji: 'so', translated: '\u305D', isBig: true},
  ],
  ta: [
    {romaji: 'ta', translated: '\u305F', isBig: true},
    {romaji: 'chi', translated: '\u3061', isBig: true},
    {romaji: 'tsu', translated: '\u3064', isBig: true},
    {romaji: 'te', translated: '\u3066', isBig: true},
    {romaji: 'to', translated: '\u3068', isBig: true},
  ],
  na: [
    {romaji: 'na', translated: '\u306A', isBig: true},
    {romaji: 'ni', translated: '\u306B', isBig: true},
    {romaji: 'nu', translated: '\u306C', isBig: true},
    {romaji: 'ne', translated: '\u306D', isBig: true},
    {romaji: 'no', translated: '\u306E', isBig: true},
  ],
  ha: [
    {romaji: 'ha', translated: '\u306F', isBig: true},
    {romaji: 'hi', translated: '\u3072', isBig: true},
    {romaji: 'fu', translated: '\u3075', isBig: true},
    {romaji: 'he', translated: '\u3078', isBig: true},
    {romaji: 'ho', translated: '\u307B', isBig: true},
  ],
  ma: [
    {romaji: 'ma', translated: '\u307E', isBig: true},
    {romaji: 'mi', translated: '\u307F', isBig: true},
    {romaji: 'mu', translated: '\u3080', isBig: true},
    {romaji: 'me', translated: '\u3081', isBig: true},
    {romaji: 'mo', translated: '\u3082', isBig: true},
  ],
  ya: [
    {romaji: 'ya', translated: '\u3084', isBig: true},
    {romaji: 'yu', translated: '\u3086', isBig: true},
    {romaji: 'yo', translated: '\u3088', isBig: true},
  ],
  ra: [
    {romaji: 'ra', translated: '\u3089', isBig: true},
    {romaji: 'ri', translated: '\u308A', isBig: true},
    {romaji: 'ru', translated: '\u308B', isBig: true},
    {romaji: 're', translated: '\u308C', isBig: true},
    {romaji: 'ro', translated: '\u308D', isBig: true},
  ],
  wa: [
    {romaji: 'wa', translated: '\u308F', isBig: true},
    {romaji: 'wo', translated: '\u3092', isBig: true},
    {romaji: 'n', translated: '\u3093', isBig: true},
  ],
}

export const katakanaList = {
  a: [
    {romaji: 'A', translated: '\u30A2', isBig: true},
    {romaji: 'I', translated: '\u30A4', isBig: true},
    {romaji: 'U', translated: '\u30A6', isBig: true},
    {romaji: 'E', translated: '\u30A8', isBig: true},
    {romaji: 'O', translated: '\u30AA', isBig: true},
  ],
  ka: [
    {romaji: 'KA', translated: '\u30AB', isBig: true},
    {romaji: 'KI', translated: '\u30AD', isBig: true},
    {romaji: 'KU', translated: '\u30AF', isBig: true},
    {romaji: 'KE', translated: '\u30B1', isBig: true},
    {romaji: 'KO', translated: '\u30B3', isBig: true},
  ],
  sa: [
    {romaji: 'SA', translated: '\u30B5', isBig: true},
    {romaji: 'SHI', translated: '\u30B7', isBig: true},
    {romaji: 'SU', translated: '\u30B9', isBig: true},
    {romaji: 'SE', translated: '\u30BB', isBig: true},
    {romaji: 'SO', translated: '\u30BD', isBig: true},
  ],
  ta: [
    {romaji: 'TA', translated: '\u30BF', isBig: true},
    {romaji: 'CHI', translated: '\u30C1', isBig: true},
    {romaji: 'TSU', translated: '\u30C4', isBig: true},
    {romaji: 'TE', translated: '\u30C6', isBig: true},
    {romaji: 'TO', translated: '\u30C8', isBig: true},
  ],
  na: [
    {romaji: 'NA', translated: '\u30CA', isBig: true},
    {romaji: 'NI', translated: '\u30CB', isBig: true},
    {romaji: 'NU', translated: '\u30CC', isBig: true},
    {romaji: 'NE', translated: '\u30CD', isBig: true},
    {romaji: 'NO', translated: '\u30CE', isBig: true},
  ],
  ha: [
    {romaji: 'HA', translated: '\u30CF', isBig: true},
    {romaji: 'HI', translated: '\u30D2', isBig: true},
    {romaji: 'FU', translated: '\u30D5', isBig: true},
    {romaji: 'HE', translated: '\u30D8', isBig: true},
    {romaji: 'HO', translated: '\u30DB', isBig: true},
  ],
  ma: [
    {romaji: 'MA', translated: '\u30DE', isBig: true},
    {romaji: 'MI', translated: '\u30DF', isBig: true},
    {romaji: 'MU', translated: '\u30E0', isBig: true},
    {romaji: 'ME', translated: '\u30E1', isBig: true},
    {romaji: 'MO', translated: '\u30E2', isBig: true},
  ],
  ya: [
    {romaji: 'YA', translated: '\u30E4', isBig: true},
    {romaji: 'YU', translated: '\u30E6', isBig: true},
    {romaji: 'YO', translated: '\u30E8', isBig: true},
  ],
  ra: [
    {romaji: 'RA', translated: '\u30E9', isBig: true},
    {romaji: 'RI', translated: '\u30EA', isBig: true},
    {romaji: 'RU', translated: '\u30EB', isBig: true},
    {romaji: 'RE', translated: '\u30EC', isBig: true},
    {romaji: 'RO', translated: '\u30ED', isBig: true},
  ],
  wa: [
    {romaji: 'WA', translated: '\u30EF', isBig: true},
    {romaji: 'WO', translated: '\u30F2', isBig: true},
    {romaji: 'N', translated: '\u30F3', isBig: true},
  ],
}

export const vocabularyList = {
  Kanji: [
    {romaji: 'La personne', translated: '人\nhito', isBig: true},
    {romaji: 'Sabre', translated: '刀\nkatana', isBig: true},
    {romaji: 'Montagne', translated: '山\nyama', isBig: true},
    {romaji: 'Rivière', translated: '川\nkawa', isBig: true},
    {romaji: 'Femme', translated: '女\nonna', isBig: true},
    {romaji: "Enfant", translated: '子\nko', isBig: true},
    {romaji: 'Terre (élément)', translated: '土\ntsuchi', isBig: true},
    {romaji: 'Feu', translated: '火\nhi', isBig: true},
    {romaji: "Eau", translated: '水\nmizu', isBig: true},
    {romaji: "Arbre", translated: '木\nki', isBig: true},
    {romaji: 'Soleil', translated: '日\nhi', isBig: true},
    {romaji: 'Lune', translated: '月\ntsuki', isBig: true},
    {romaji: 'Fleur', translated: '花\nhana', isBig: true},
    {romaji: 'Homme', translated: '男\notoko', isBig: true},
    {romaji: 'Ciel', translated: '空\nsora', isBig: true},
    {romaji: "Argent (monnaie)", translated: '金\n(o)kane', isBig: true},
    {romaji: 'Pluie', translated: '雨\name', isBig: true},
    {romaji: 'Vent', translated: '風\nkaze', isBig: true},
    {romaji: 'Temps', translated: '時\ntoki', isBig: true},
    {romaji: 'Neige', translated: '雪\nyuki', isBig: true},
  ],
  'Formules de politesses': [
    {romaji: 'Bonjour\n(journée)', translated: 'こんにちは\nkonichiwa'},
    {romaji: 'Non', translated: 'いいえ\niie'},
    {romaji: 'S\'il vous plaît', translated: 'おねがいします\nonegai shimasu'},
    {romaji: 'Merci', translated: 'ありがとうございます\narigatô gozaimasu'},
    {romaji: 'Il n\'y a pas de quoi', translated: 'どういたしまして\ndô itashimashite'},
    {romaji: 'Bonjour\n(matin)', translated: 'おはようございます\nohayô gozaimasu'},
    {romaji: 'Bonsoir', translated: 'こんばんは\nkonbanwa '},
    {romaji: 'Comment vas tu ?', translated: 'おげんきですか\nogenki desu ka'},
    {romaji: 'Je vais bien', translated: 'はいげんきです\nhai genki desu'},
    {romaji: 'Au revoir\n(adieu)', translated: 'さようなら\nsayônara'},
    {romaji: 'Au revoir\n(à la prochaine)', translated: 'またね\nmatane'},
    {romaji: 'Bonne nuit', translated: 'おやすみなさい\noyasumi nasai'},
    {romaji: 'A demain', translated: 'またあした\nmata ashita'},
    {romaji: 'Enchanté\n(1ere rencontre)', translated: 'はじめまして\nhajimemashite'},
    {romaji: 'Ravi de faire votre connaissance', translated: 'どうぞよろしくおねがいします\ndôzo yoroshiku onegai shimasu'},
    {romaji: 'Je vous en prie\n(après vous)', translated: 'どうぞ\ndôzo'},
    {romaji: 'Bon appétit', translated: 'いただきます\nitadakimasu'},
    {romaji: 'Excusez moi', translated: 'すみません\nsumimasen'},
    {romaji: 'Pardonnez moi', translated: 'ごめんなさい\ngomen nasai'},
    {romaji: 'Bon travail', translated: 'おつかれさまでした\notsukare sama deshita'},
    {romaji: 'J\'y vais\n(maison)', translated: 'いってきます\nittekimasu'},
    {romaji: 'Bonne journée\n(maison)', translated: 'いってらっしゃい\nitterasshai'},
    {romaji: 'Je suis rentré', translated: 'ただいま\ntadaima'},
    {romaji: 'Bon retour\n(maison)', translated: 'おかえりなさい\nokaeri nasai'},
    {romaji: 'Bienvenue\n(magasin)', translated: 'いらっしゃいませ\nirasshaimase'},
    {romaji: 'Bienvenue\n(général)', translated: 'ようこそ\nyôkoso'},
    {romaji: 'Je rentre\n(chez quelqu\'un dautre)', translated: 'おじゃまします\nojama shimasu'},
     ],
  'Matériel domestique': [
    {romaji: 'Lit', translated: 'ベッド\nBEDDO'},
    {romaji: 'Canapé', translated: 'ソファー\nSOFÂ'},
    {romaji: 'Stylo(bille)', translated: '（ボール）ぺン\n(BÔRU)PEN'},
    {romaji: 'Cahier', translated: 'ノート\nNÔTO'},
    {romaji: 'Calendrier', translated: 'カレンダー\nKARENDÂ'},
    {romaji: 'Radio', translated: 'ラジオ\nRAJIO'},
    {romaji: 'Chaine hi-fi', translated: 'ステレオ\nSUTEREO'},
    {romaji: 'Télévision', translated: 'テレビ\nTEREBI'},
    {romaji: 'Appareil photo', translated: 'カメラ\nKAMERA'},
    {romaji: 'Ordinateur', translated: 'コンピュータ\nKONPYÛTA'},
    {romaji: 'PC', translated: 'パソコン\nPASOKON'},
    {romaji: 'Climatiseur', translated: 'エアコン\nEAKON'},
    {romaji: 'Télécommande', translated: 'リモコン\nRIMOKON'},
    {romaji: 'Carte de paiement', translated: 'クレジットカード\nKUREJITTO KÂDO'},
    {romaji: 'Porte', translated: 'ドア\nDOA'},
    {romaji: 'Lampe', translated: 'ランプ\nRANPU'},
    {romaji: 'Table', translated: 'テーブル\nTÊBURU'},
    {romaji: 'Fourchette', translated: 'フォーク\nFÔKU'},
    {romaji: 'Couteau', translated: 'ナイフ\nNAIFU'},
    {romaji: 'Cuillère', translated: 'スプーン\nSUPÛN'},
    {romaji: 'Toilettes', translated: 'トイレ\nTOIRE'},
  ],
}
