export const hiraganaList = {
  a: [
    {romaji: 'a', kana: '\u3042'},
    {romaji: 'i', kana: '\u3044'},
    {romaji: 'u', kana: '\u3046'},
    {romaji: 'e', kana: '\u3048'},
    {romaji: 'o', kana: '\u304A'},
  ],
  ka: [
    {romaji: 'ka', kana: '\u304B'},
    {romaji: 'ki', kana: '\u304D'},
    {romaji: 'ku', kana: '\u304F'},
    {romaji: 'ke', kana: '\u3051'},
    {romaji: 'ko', kana: '\u3053'},
  ],
  sa: [
    {romaji: 'sa', kana: '\u3055'},
    {romaji: 'shi', kana: '\u3057'},
    {romaji: 'su', kana: '\u3059'},
    {romaji: 'se', kana: '\u305B'},
    {romaji: 'so', kana: '\u305D'},
  ],
  ta: [
    {romaji: 'ta', kana: '\u305F'},
    {romaji: 'chi', kana: '\u3061'},
    {romaji: 'tsu', kana: '\u3064'},
    {romaji: 'te', kana: '\u3066'},
    {romaji: 'to', kana: '\u3068'},
  ],
  na: [
    {romaji: 'na', kana: '\u306A'},
    {romaji: 'ni', kana: '\u306B'},
    {romaji: 'nu', kana: '\u306C'},
    {romaji: 'ne', kana: '\u306D'},
    {romaji: 'no', kana: '\u306E'},
  ],
  ha: [
    {romaji: 'ha', kana: '\u306F'},
    {romaji: 'hi', kana: '\u3072'},
    {romaji: 'fu', kana: '\u3075'},
    {romaji: 'he', kana: '\u3078'},
    {romaji: 'ho', kana: '\u307B'},
  ],
  ma: [
    {romaji: 'ma', kana: '\u307E'},
    {romaji: 'mi', kana: '\u307F'},
    {romaji: 'mu', kana: '\u3080'},
    {romaji: 'me', kana: '\u3081'},
    {romaji: 'mo', kana: '\u3082'},
  ],
  ya: [
    {romaji: 'ya', kana: '\u3084'},
    {romaji: 'yu', kana: '\u3086'},
    {romaji: 'yo', kana: '\u3088'},
  ],
  ra: [
    {romaji: 'ra', kana: '\u3089'},
    {romaji: 'ri', kana: '\u308A'},
    {romaji: 'ru', kana: '\u308B'},
    {romaji: 're', kana: '\u308C'},
    {romaji: 'ro', kana: '\u308D'},
  ],
  wa: [
    {romaji: 'wa', kana: '\u308F'},
    {romaji: 'wo', kana: '\u3092'},
    {romaji: 'n', kana: '\u3093'},
  ],
}

export const katakanaList = {
  a: [
    {romaji: 'A', kana: '\u30A2'},
    {romaji: 'I', kana: '\u30A4'},
    {romaji: 'U', kana: '\u30A6'},
    {romaji: 'E', kana: '\u30A8'},
    {romaji: 'O', kana: '\u30AA'},
  ],
  ka: [
    {romaji: 'KA', kana: '\u30AB'},
    {romaji: 'KI', kana: '\u30AD'},
    {romaji: 'KU', kana: '\u30AF'},
    {romaji: 'KE', kana: '\u30B1'},
    {romaji: 'KO', kana: '\u30B3'},
  ],
  sa: [
    {romaji: 'SA', kana: '\u30B5'},
    {romaji: 'SHI', kana: '\u30B7'},
    {romaji: 'SU', kana: '\u30B9'},
    {romaji: 'SE', kana: '\u30BB'},
    {romaji: 'SO', kana: '\u30BD'},
  ],
  ta: [
    {romaji: 'TA', kana: '\u30BF'},
    {romaji: 'CHI', kana: '\u30C1'},
    {romaji: 'TSU', kana: '\u30C4'},
    {romaji: 'TE', kana: '\u30C6'},
    {romaji: 'TO', kana: '\u30C8'},
  ],
  na: [
    {romaji: 'NA', kana: '\u30CA'},
    {romaji: 'NI', kana: '\u30CB'},
    {romaji: 'NU', kana: '\u30CC'},
    {romaji: 'NE', kana: '\u30CD'},
    {romaji: 'NO', kana: '\u30CE'},
  ],
  ha: [
    {romaji: 'HA', kana: '\u30CF'},
    {romaji: 'HI', kana: '\u30D2'},
    {romaji: 'FU', kana: '\u30D5'},
    {romaji: 'HE', kana: '\u30D8'},
    {romaji: 'HO', kana: '\u30DB'},
  ],
  ma: [
    {romaji: 'MA', kana: '\u30DE'},
    {romaji: 'MI', kana: '\u30DF'},
    {romaji: 'MU', kana: '\u30E0'},
    {romaji: 'ME', kana: '\u30E1'},
    {romaji: 'MO', kana: '\u30E2'},
  ],
  ya: [
    {romaji: 'YA', kana: '\u30E4'},
    {romaji: 'YU', kana: '\u30E6'},
    {romaji: 'YO', kana: '\u30E8'},
  ],
  ra: [
    {romaji: 'RA', kana: '\u30E9'},
    {romaji: 'RI', kana: '\u30EA'},
    {romaji: 'RU', kana: '\u30EB'},
    {romaji: 'RE', kana: '\u30EC'},
    {romaji: 'RO', kana: '\u30ED'},
  ],
  wa: [
    {romaji: 'WA', kana: '\u30EF'},
    {romaji: 'WO', kana: '\u30F2'},
    {romaji: 'N', kana: '\u30F3'},
  ],
}
